### ISSUE TITLE
Why not jwt?

### ISSUE THREAD

**Issue by juanda99** [rusty1s/koa2-oauth2-rest-api#1]
I trying to make a rest api similar to yours...
Shouldn't be better to use JWT instead of bearer and not saving into database?

Why do you put the profile in the strategy instead of callbackURL [as is in the docs](https://github.com/jaredhanson/passport-facebook)?

```
passport.use(new FacebookStrategy({
    clientID: FACEBOOK_APP_ID,
    clientSecret: FACEBOOK_APP_SECRET,
    callbackURL: "http://localhost:3000/auth/facebook/callback"
  },
  function(accessToken, refreshToken, profile, cb) {
    User.findOrCreate({ facebookId: profile.id }, function (err, user) {
      return cb(err, user);
    });
  }
));
` ``
```

**Comment by juanda99** [comment]
Upps, I see profile field in the strategy class is to get displayName!

**Comment by rusty1s** [comment]
This repository is still in development, so nothing is set in stone yet. I'm working on implementing the code and token grant for oauth2 at the moment and bearer is the preferred strategy for oauth2. I might consider jwt in the near future.
