### ISSUE TITLE
Facebook Graph Request

### ISSUE THREAD

**Issue by sibelius** [rusty1s/koa2-oauth2-rest-api#2]
Great repo!

How are you going to do facebook graph request after getting user accesstoken ?

**Comment by rusty1s** [comment]
Hi and thank you. Sorry, that I didn't answer you till now, I had a lot of work to do.

I don't have any experience with graph requests yet, so you may collect your information about them from the facebook developer page and `passport-facebook`. I will add it to my todo list, but don't expect it to be released anytime soon. This repo is still in development and there are other tasks that needs to be addressed first.
